"""empty message

Revision ID: 4dd8d032af91
Revises: ce6f5e95b530
Create Date: 2019-12-22 07:03:21.714901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dd8d032af91'
down_revision = 'ce6f5e95b530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amplitudes', schema=None) as batch_op:
        batch_op.drop_column('R_L')
        batch_op.drop_column('R_TLp')
        batch_op.drop_column('R_TL')
        batch_op.drop_column('R_TT')
        batch_op.drop_column('R_T')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amplitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('R_T', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('R_TT', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('R_TL', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('R_TLp', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('R_L', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
