"""initial

Revision ID: ce6f5e95b530
Revises: 
Create Date: 2019-09-04 20:59:20.376323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6f5e95b530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('mdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html', sa.String(length=255), nullable=True),
    sa.Column('html_plain', sa.String(length=255), nullable=True),
    sa.Column('tex', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('name', name=op.f('uq_channels_name'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('mdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('name', name=op.f('uq_models_name'))
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('mdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html', sa.String(length=255), nullable=True),
    sa.Column('html_plain', sa.String(length=255), nullable=True),
    sa.Column('tex', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('name', name=op.f('uq_units_name'))
    )
    op.create_table('amplitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Float(), nullable=True),
    sa.Column('w', sa.Float(), nullable=True),
    sa.Column('cos_theta', sa.Float(), nullable=True),
    sa.Column('H1r', sa.Float(), nullable=True),
    sa.Column('H1j', sa.Float(), nullable=True),
    sa.Column('H2r', sa.Float(), nullable=True),
    sa.Column('H2j', sa.Float(), nullable=True),
    sa.Column('H3r', sa.Float(), nullable=True),
    sa.Column('H3j', sa.Float(), nullable=True),
    sa.Column('H4r', sa.Float(), nullable=True),
    sa.Column('H4j', sa.Float(), nullable=True),
    sa.Column('H5r', sa.Float(), nullable=True),
    sa.Column('H5j', sa.Float(), nullable=True),
    sa.Column('H6r', sa.Float(), nullable=True),
    sa.Column('H6j', sa.Float(), nullable=True),
    sa.Column('R_T', sa.Float(), nullable=True),
    sa.Column('R_L', sa.Float(), nullable=True),
    sa.Column('R_TT', sa.Float(), nullable=True),
    sa.Column('R_TL', sa.Float(), nullable=True),
    sa.Column('R_TLp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_amplitudes_channel_id_channels')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_amplitudes_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amplitudes')),
    sa.UniqueConstraint('channel_id', 'model_id', 'q2', 'w', 'cos_theta', name='grid')
    )
    op.create_table('quantities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('mdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html', sa.String(length=255), nullable=True),
    sa.Column('html_plain', sa.String(length=255), nullable=True),
    sa.Column('tex', sa.String(length=255), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_quantities_unit_id_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quantities')),
    sa.UniqueConstraint('name', name=op.f('uq_quantities_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantities')
    op.drop_table('amplitudes')
    op.drop_table('units')
    op.drop_table('models')
    op.drop_table('channels')
    # ### end Alembic commands ###
