"""empty message

Revision ID: e96eec5dd581
Revises: 62fdebdd2d5f
Create Date: 2019-07-18 20:37:02.560475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96eec5dd581'
down_revision = '62fdebdd2d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amplitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sigma_l', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sigma_t', sa.Float(), nullable=True))
        batch_op.drop_column('sigma_u')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amplitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sigma_u', sa.FLOAT(), nullable=True))
        batch_op.drop_column('sigma_t')
        batch_op.drop_column('sigma_l')

    # ### end Alembic commands ###
